title = 'Monero Guides'
theme = "accessible-minimalism"
baseURL = "https://moneroguides.org"
languageCode = "en-us"
enableEmoji = 'true'
disableHugoGeneratorInject = true
enableRobotsTXT = true

[author]
  name = "Monero Guides"

[params]
    youtube = "https://www.youtube.com/channel/UCWeGibnI0h07pIPiX945DBg"
    github = "https://www.github.com/moneroguides"
    reddit = "https://www.reddit.com/user/moneroguides/"
    matrix = "https://www.matrix.to/#/@monero-guides:matrix.org"

