title = 'Monero Guides'
theme = "accessible-minimalism"
baseURL = "https://moneroguides.org"
languageCode = "en-us"
enableEmoji = 'true'
disableHugoGeneratorInject = true
enableRobotsTXT = true

[author]
  name = "Monero Guides"

[params]
    custom_css = ["css/reset.css", "css/main.css", "css/simple-grid.css"]
